### ISSUE TITLE
Add shutdown script

### ISSUE THREAD

**Issue by DingouerFish** [actframework/act-starter-support#18]

**Comment by greenlaw110** [comment]
Fixed, now it has a `shutdown` script once you unpack the deployment package:

![image](https://user-images.githubusercontent.com/216930/103449221-67625f80-4cf9-11eb-88e9-31e738784a19.png)

Run the script will shutdown the current app:

![image](https://user-images.githubusercontent.com/216930/103449231-852fc480-4cf9-11eb-8350-58ebc9df3f8f.png)
